- evalvue/settings.py
> changing odbc drive

- evalvue/settings.py
- info/views.py
commiting logging and designation in emoloyee
> commiting logging and designation in emoloyee

- info/constant.py
- info/employee.py
- info/organization.py
- info/response.py
- info/urls.py
- info/utility.py
- info/views.py
> Commiting Organization API

- info/apps.py
- info/utility.py
- info/views.py
> deleting unnecessary lines

- info/views.py
> adding logger

- info/organization.py
- info/utility.py
- info/views.py
> uuid added

- evalvue/settings.py
> uncomment cors or

- info/views.py
> remove jwt

- evalvue/middleware.py
- info/response.py
- info/urls.py
- info/views.py
> editable data apis

- info/organization.py
- info/utility.py
- info/views.py
> validate image

- info/common_regex.py
- info/utility.py
- info/views.py
> add regex for gstin

- evalvue/settings.py
- info/constant.py
change database root for test.api
> change database root for test.api

- info/common_regex.py
- info/employee.py
- info/utility.py
- info/views.py
> first name last name employee

- info/views.py
> editable organization data

- info/common_regex.py
> change in gstin regex

- evalvue/settings.py
> production setting

- info/apps.py
- info/cache.py
- info/common_regex.py
- info/views.py
> adding referral feature

- evalvue/middleware.py
- info/organization.py
- info/response.py
- info/urls.py
- info/views.py
> API for document verification

- info/views.py
working on document verification api
> working on document verification api

- info/payment.py
- info/response.py
- info/urls.py
- info/views.py
> payment history api

- evalvue/settings.py
> prod setting
